// Generated by npm run build:cache. Public assets only; no auth/API caching.
const CACHE = "inventario-parejas-shell-efd5717931b2fa69";
const ASSETS = [
  "./",
  "./icon-192x192.png",
  "./icon-512x512.png",
  "./index.html",
  "./logo.png",
  "./manifest.json",
  "./src/additional-rules.js",
  "./src/app.js",
  "./src/asset-status.js",
  "./src/backup-details.js",
  "./src/backups.js",
  "./src/camera.js",
  "./src/data.js",
  "./src/excel-import.js",
  "./src/listings.js",
  "./src/location-edit.js",
  "./src/mobile.js",
  "./src/official-reports.js",
  "./src/operations.js",
  "./src/output.js",
  "./src/people.js",
  "./src/platform.js",
  "./src/progress.js",
  "./src/recovery.js",
  "./src/report-assets/inventarios.png",
  "./src/report-assets/resguardo.png",
  "./src/retag.js",
  "./src/review.js",
  "./src/rfid-core.js",
  "./src/rfid-store.js",
  "./src/rfid-ui.js",
  "./src/rfid-worker.js",
  "./src/safe-changes.js",
  "./src/search.js",
  "./src/storage.js",
  "./src/team.js",
  "./styles/actions.css",
  "./styles/app.css",
  "./styles/mobile.css",
  "./styles/rfid.css",
  "./styles/theme.css",
  "./styles/utilities.css",
  "./vendor/fontawesome/css/all.min.css",
  "./vendor/fontawesome/webfonts/fa-brands-400.woff2",
  "./vendor/fontawesome/webfonts/fa-regular-400.woff2",
  "./vendor/fontawesome/webfonts/fa-solid-900.woff2",
  "./vendor/fontawesome/webfonts/fa-v4compatibility.woff2",
  "./vendor/html5-qrcode.js",
  "./vendor/jszip.js",
  "./vendor/qrcode.js",
  "./vendor/sources.json",
  "./vendor/xlsx.js"
];
const URLS = new Set(ASSETS.map(p => new URL(p, self.registration.scope).href));
self.addEventListener('message', event => { if(event.data?.type === 'ACTIVATE_UPDATE') self.skipWaiting(); });
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(ASSETS.map(url => new Request(url, {cache:'reload'})))));
  // Wait for old tabs to close; do not replace code during an inventory capture.
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith('inventario-parejas-shell-') && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET' || !URLS.has(event.request.url)) return;
  event.respondWith(caches.open(CACHE).then(async cache => (await cache.match(event.request)) || fetch(event.request)));
});

